Dev/master ecbuild sync
JCSDA-internal/MOM6 pull request #4
Opened 2019-07-31 18:28 UTC by aerorahul

syncing NOAA-GFDL/mom6::dev/master with JCSDA/mom6::dev/master and then updating JCSDA/mom6::dev/master-ecbuild

There are extensive changes in MOM6.
There were no conflicts (amazingly).  We should cron this repo to automagically sync, if we wish to remain in sync with them.  Sooner (or later) we will deal directly with a coupled model (either UFS or GEOS), and this may become moot, but until then, this needs doing every so often.

Suggestions?

2019-08-01 13:47 UTC, travissluka commented
I'm getting an error when I try to build
```
CMake Error at /usr/local/share/ecbuild/cmake/ecbuild_add_library.cmake:270 (add_library):
  Cannot find source file:

    src/user/SCM_CVmix_tests.F90
```

2019-08-01 14:00 UTC, travissluka commented on src/CMakeLists.txt
>  src/user/SCM_CVmix_tests.F90
```suggestion
src/user/SCM_CVMix_tests.F90
```

2019-08-01 14:16 UTC, travissluka requested changes
Some of the interfaces have changed slightly. We'll have to prepare changes in SOCA first before merging this in.

2019-08-01 16:52 UTC, aerorahul commented
@travissluka I agree we should update SOCA interfaces before merging this branch.
I can work on exploring which interfaces need to be updated and how many they are.

2019-08-01 17:05 UTC, guillaumevernieres commented
Sounds good @aerorahul , thanks for doing that work.

2019-08-01 19:15 UTC, aerorahul commented
@travissluka @guillaumevernieres 
See branch `soca::feature/mom6-change` that incorporates the changes in MOM6 into the SOCA interface.

2019-08-09 14:20 UTC, travissluka approved these changes

2019-08-09 14:20 UTC, merged